/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareRouteImport } from './routes/care'
import { Route as CareTeamRouteImport } from './routes/care-team'
import { Route as CompanionRouteImport } from './routes/companion'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as GeofenceRouteImport } from './routes/geofence'
import { Route as HomeRouteImport } from './routes/home'
import { Route as MedicationRouteImport } from './routes/medication'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as TwinRouteImport } from './routes/twin'
import { Route as CareTeamIndexRouteImport } from './routes/care-team.index'
import { Route as CareTeamCaregiversRouteImport } from './routes/care-team.caregivers'
import { Route as CareTeamFindRouteImport } from './routes/care-team.find'
import { Route as CareTeamRequestSentRouteImport } from './routes/care-team.request-sent'
import { Route as CareIndexRouteImport } from './routes/care.index'
import { Route as CareProgramRouteImport } from './routes/care.$program'
import { Route as FamilyIndexRouteImport } from './routes/family.index'
import { Route as FamilyMemberIdRouteImport } from './routes/family.$memberId'
import { Route as GeofenceIndexRouteImport } from './routes/geofence.index'
import { Route as GeofenceAlertsRouteImport } from './routes/geofence.alerts'
import { Route as GeofenceSettingsRouteImport } from './routes/geofence.settings'
import { Route as GeofenceZonesRouteImport } from './routes/geofence.zones'
import { Route as MedicationIndexRouteImport } from './routes/medication.index'
import { Route as MedicationAddRouteImport } from './routes/medication.add'
import { Route as MedicationCourseRouteImport } from './routes/medication.course'
import { Route as MedicationHistoryRouteImport } from './routes/medication.history'
import { Route as MedicationRefillsRouteImport } from './routes/medication.refills'
import { Route as MedicationRemindersRouteImport } from './routes/medication.reminders'
import { Route as MedicationReviewRouteImport } from './routes/medication.review'
import { Route as ProfileSectionRouteImport } from './routes/profile.$section'
import { Route as RecordsIndexRouteImport } from './routes/records.index'
import { Route as RecordsCategoryRouteImport } from './routes/records.$category'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as TwinSystemRouteImport } from './routes/twin.$system'
import { Route as VitalsMetricRouteImport } from './routes/vitals.$metric'
import { Route as CareTeamCaregiverCaregiverIdRouteImport } from './routes/care-team.caregiver.$caregiverId'
import { Route as RecordsDocIdRouteImport } from './routes/records.doc.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const CareTeamRoute = CareTeamRouteImport.update({
  id: '/care-team',
  path: '/care-team',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionRoute = CompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const GeofenceRoute = GeofenceRouteImport.update({
  id: '/geofence',
  path: '/geofence',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationRoute = MedicationRouteImport.update({
  id: '/medication',
  path: '/medication',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TwinRoute = TwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => rootRouteImport,
} as any)
const CareTeamIndexRoute = CareTeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareTeamRoute,
} as any)
const CareTeamCaregiversRoute = CareTeamCaregiversRouteImport.update({
  id: '/caregivers',
  path: '/caregivers',
  getParentRoute: () => CareTeamRoute,
} as any)
const CareTeamFindRoute = CareTeamFindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => CareTeamRoute,
} as any)
const CareTeamRequestSentRoute = CareTeamRequestSentRouteImport.update({
  id: '/request-sent',
  path: '/request-sent',
  getParentRoute: () => CareTeamRoute,
} as any)
const CareIndexRoute = CareIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareRoute,
} as any)
const CareProgramRoute = CareProgramRouteImport.update({
  id: '/$program',
  path: '/$program',
  getParentRoute: () => CareRoute,
} as any)
const FamilyIndexRoute = FamilyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FamilyRoute,
} as any)
const FamilyMemberIdRoute = FamilyMemberIdRouteImport.update({
  id: '/$memberId',
  path: '/$memberId',
  getParentRoute: () => FamilyRoute,
} as any)
const GeofenceIndexRoute = GeofenceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GeofenceRoute,
} as any)
const GeofenceAlertsRoute = GeofenceAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => GeofenceRoute,
} as any)
const GeofenceSettingsRoute = GeofenceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => GeofenceRoute,
} as any)
const GeofenceZonesRoute = GeofenceZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => GeofenceRoute,
} as any)
const MedicationIndexRoute = MedicationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MedicationRoute,
} as any)
const MedicationAddRoute = MedicationAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => MedicationRoute,
} as any)
const MedicationCourseRoute = MedicationCourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => MedicationRoute,
} as any)
const MedicationHistoryRoute = MedicationHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => MedicationRoute,
} as any)
const MedicationRefillsRoute = MedicationRefillsRouteImport.update({
  id: '/refills',
  path: '/refills',
  getParentRoute: () => MedicationRoute,
} as any)
const MedicationRemindersRoute = MedicationRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => MedicationRoute,
} as any)
const MedicationReviewRoute = MedicationReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => MedicationRoute,
} as any)
const ProfileSectionRoute = ProfileSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => ProfileRoute,
} as any)
const RecordsIndexRoute = RecordsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecordsRoute,
} as any)
const RecordsCategoryRoute = RecordsCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => RecordsRoute,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReportsRoute,
} as any)
const TwinSystemRoute = TwinSystemRouteImport.update({
  id: '/$system',
  path: '/$system',
  getParentRoute: () => TwinRoute,
} as any)
const VitalsMetricRoute = VitalsMetricRouteImport.update({
  id: '/vitals/$metric',
  path: '/vitals/$metric',
  getParentRoute: () => rootRouteImport,
} as any)
const CareTeamCaregiverCaregiverIdRoute =
  CareTeamCaregiverCaregiverIdRouteImport.update({
    id: '/caregiver/$caregiverId',
    path: '/caregiver/$caregiverId',
    getParentRoute: () => CareTeamRoute,
  } as any)
const RecordsDocIdRoute = RecordsDocIdRouteImport.update({
  id: '/doc/$id',
  path: '/doc/$id',
  getParentRoute: () => RecordsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/care': typeof CareRouteWithChildren
  '/care-team': typeof CareTeamRouteWithChildren
  '/companion': typeof CompanionRoute
  '/family': typeof FamilyRouteWithChildren
  '/geofence': typeof GeofenceRouteWithChildren
  '/home': typeof HomeRoute
  '/medication': typeof MedicationRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRouteWithChildren
  '/records': typeof RecordsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/twin': typeof TwinRouteWithChildren
  '/care-team/caregivers': typeof CareTeamCaregiversRoute
  '/care-team/find': typeof CareTeamFindRoute
  '/care-team/request-sent': typeof CareTeamRequestSentRoute
  '/care/$program': typeof CareProgramRoute
  '/family/$memberId': typeof FamilyMemberIdRoute
  '/geofence/alerts': typeof GeofenceAlertsRoute
  '/geofence/settings': typeof GeofenceSettingsRoute
  '/geofence/zones': typeof GeofenceZonesRoute
  '/medication/add': typeof MedicationAddRoute
  '/medication/course': typeof MedicationCourseRoute
  '/medication/history': typeof MedicationHistoryRoute
  '/medication/refills': typeof MedicationRefillsRoute
  '/medication/reminders': typeof MedicationRemindersRoute
  '/medication/review': typeof MedicationReviewRoute
  '/profile/$section': typeof ProfileSectionRoute
  '/records/$category': typeof RecordsCategoryRoute
  '/reports/$id': typeof ReportsIdRoute
  '/twin/$system': typeof TwinSystemRoute
  '/vitals/$metric': typeof VitalsMetricRoute
  '/care-team/': typeof CareTeamIndexRoute
  '/care/': typeof CareIndexRoute
  '/family/': typeof FamilyIndexRoute
  '/geofence/': typeof GeofenceIndexRoute
  '/medication/': typeof MedicationIndexRoute
  '/records/': typeof RecordsIndexRoute
  '/care-team/caregiver/$caregiverId': typeof CareTeamCaregiverCaregiverIdRoute
  '/records/doc/$id': typeof RecordsDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/companion': typeof CompanionRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/twin': typeof TwinRouteWithChildren
  '/care-team/caregivers': typeof CareTeamCaregiversRoute
  '/care-team/find': typeof CareTeamFindRoute
  '/care-team/request-sent': typeof CareTeamRequestSentRoute
  '/care/$program': typeof CareProgramRoute
  '/family/$memberId': typeof FamilyMemberIdRoute
  '/geofence/alerts': typeof GeofenceAlertsRoute
  '/geofence/settings': typeof GeofenceSettingsRoute
  '/geofence/zones': typeof GeofenceZonesRoute
  '/medication/add': typeof MedicationAddRoute
  '/medication/course': typeof MedicationCourseRoute
  '/medication/history': typeof MedicationHistoryRoute
  '/medication/refills': typeof MedicationRefillsRoute
  '/medication/reminders': typeof MedicationRemindersRoute
  '/medication/review': typeof MedicationReviewRoute
  '/profile/$section': typeof ProfileSectionRoute
  '/records/$category': typeof RecordsCategoryRoute
  '/reports/$id': typeof ReportsIdRoute
  '/twin/$system': typeof TwinSystemRoute
  '/vitals/$metric': typeof VitalsMetricRoute
  '/care-team': typeof CareTeamIndexRoute
  '/care': typeof CareIndexRoute
  '/family': typeof FamilyIndexRoute
  '/geofence': typeof GeofenceIndexRoute
  '/medication': typeof MedicationIndexRoute
  '/records': typeof RecordsIndexRoute
  '/care-team/caregiver/$caregiverId': typeof CareTeamCaregiverCaregiverIdRoute
  '/records/doc/$id': typeof RecordsDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/care': typeof CareRouteWithChildren
  '/care-team': typeof CareTeamRouteWithChildren
  '/companion': typeof CompanionRoute
  '/family': typeof FamilyRouteWithChildren
  '/geofence': typeof GeofenceRouteWithChildren
  '/home': typeof HomeRoute
  '/medication': typeof MedicationRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRouteWithChildren
  '/records': typeof RecordsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/twin': typeof TwinRouteWithChildren
  '/care-team/caregivers': typeof CareTeamCaregiversRoute
  '/care-team/find': typeof CareTeamFindRoute
  '/care-team/request-sent': typeof CareTeamRequestSentRoute
  '/care/$program': typeof CareProgramRoute
  '/family/$memberId': typeof FamilyMemberIdRoute
  '/geofence/alerts': typeof GeofenceAlertsRoute
  '/geofence/settings': typeof GeofenceSettingsRoute
  '/geofence/zones': typeof GeofenceZonesRoute
  '/medication/add': typeof MedicationAddRoute
  '/medication/course': typeof MedicationCourseRoute
  '/medication/history': typeof MedicationHistoryRoute
  '/medication/refills': typeof MedicationRefillsRoute
  '/medication/reminders': typeof MedicationRemindersRoute
  '/medication/review': typeof MedicationReviewRoute
  '/profile/$section': typeof ProfileSectionRoute
  '/records/$category': typeof RecordsCategoryRoute
  '/reports/$id': typeof ReportsIdRoute
  '/twin/$system': typeof TwinSystemRoute
  '/vitals/$metric': typeof VitalsMetricRoute
  '/care-team/': typeof CareTeamIndexRoute
  '/care/': typeof CareIndexRoute
  '/family/': typeof FamilyIndexRoute
  '/geofence/': typeof GeofenceIndexRoute
  '/medication/': typeof MedicationIndexRoute
  '/records/': typeof RecordsIndexRoute
  '/care-team/caregiver/$caregiverId': typeof CareTeamCaregiverCaregiverIdRoute
  '/records/doc/$id': typeof RecordsDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/care'
    | '/care-team'
    | '/companion'
    | '/family'
    | '/geofence'
    | '/home'
    | '/medication'
    | '/notifications'
    | '/onboarding'
    | '/premium'
    | '/profile'
    | '/records'
    | '/reports'
    | '/twin'
    | '/care-team/caregivers'
    | '/care-team/find'
    | '/care-team/request-sent'
    | '/care/$program'
    | '/family/$memberId'
    | '/geofence/alerts'
    | '/geofence/settings'
    | '/geofence/zones'
    | '/medication/add'
    | '/medication/course'
    | '/medication/history'
    | '/medication/refills'
    | '/medication/reminders'
    | '/medication/review'
    | '/profile/$section'
    | '/records/$category'
    | '/reports/$id'
    | '/twin/$system'
    | '/vitals/$metric'
    | '/care-team/'
    | '/care/'
    | '/family/'
    | '/geofence/'
    | '/medication/'
    | '/records/'
    | '/care-team/caregiver/$caregiverId'
    | '/records/doc/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/companion'
    | '/home'
    | '/notifications'
    | '/onboarding'
    | '/premium'
    | '/profile'
    | '/reports'
    | '/twin'
    | '/care-team/caregivers'
    | '/care-team/find'
    | '/care-team/request-sent'
    | '/care/$program'
    | '/family/$memberId'
    | '/geofence/alerts'
    | '/geofence/settings'
    | '/geofence/zones'
    | '/medication/add'
    | '/medication/course'
    | '/medication/history'
    | '/medication/refills'
    | '/medication/reminders'
    | '/medication/review'
    | '/profile/$section'
    | '/records/$category'
    | '/reports/$id'
    | '/twin/$system'
    | '/vitals/$metric'
    | '/care-team'
    | '/care'
    | '/family'
    | '/geofence'
    | '/medication'
    | '/records'
    | '/care-team/caregiver/$caregiverId'
    | '/records/doc/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/care'
    | '/care-team'
    | '/companion'
    | '/family'
    | '/geofence'
    | '/home'
    | '/medication'
    | '/notifications'
    | '/onboarding'
    | '/premium'
    | '/profile'
    | '/records'
    | '/reports'
    | '/twin'
    | '/care-team/caregivers'
    | '/care-team/find'
    | '/care-team/request-sent'
    | '/care/$program'
    | '/family/$memberId'
    | '/geofence/alerts'
    | '/geofence/settings'
    | '/geofence/zones'
    | '/medication/add'
    | '/medication/course'
    | '/medication/history'
    | '/medication/refills'
    | '/medication/reminders'
    | '/medication/review'
    | '/profile/$section'
    | '/records/$category'
    | '/reports/$id'
    | '/twin/$system'
    | '/vitals/$metric'
    | '/care-team/'
    | '/care/'
    | '/family/'
    | '/geofence/'
    | '/medication/'
    | '/records/'
    | '/care-team/caregiver/$caregiverId'
    | '/records/doc/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CareRoute: typeof CareRouteWithChildren
  CareTeamRoute: typeof CareTeamRouteWithChildren
  CompanionRoute: typeof CompanionRoute
  FamilyRoute: typeof FamilyRouteWithChildren
  GeofenceRoute: typeof GeofenceRouteWithChildren
  HomeRoute: typeof HomeRoute
  MedicationRoute: typeof MedicationRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PremiumRoute: typeof PremiumRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RecordsRoute: typeof RecordsRouteWithChildren
  ReportsRoute: typeof ReportsRouteWithChildren
  TwinRoute: typeof TwinRouteWithChildren
  VitalsMetricRoute: typeof VitalsMetricRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-team': {
      id: '/care-team'
      path: '/care-team'
      fullPath: '/care-team'
      preLoaderRoute: typeof CareTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion': {
      id: '/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geofence': {
      id: '/geofence'
      path: '/geofence'
      fullPath: '/geofence'
      preLoaderRoute: typeof GeofenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medication': {
      id: '/medication'
      path: '/medication'
      fullPath: '/medication'
      preLoaderRoute: typeof MedicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twin': {
      id: '/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof TwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-team/': {
      id: '/care-team/'
      path: '/'
      fullPath: '/care-team/'
      preLoaderRoute: typeof CareTeamIndexRouteImport
      parentRoute: typeof CareTeamRoute
    }
    '/care-team/caregivers': {
      id: '/care-team/caregivers'
      path: '/caregivers'
      fullPath: '/care-team/caregivers'
      preLoaderRoute: typeof CareTeamCaregiversRouteImport
      parentRoute: typeof CareTeamRoute
    }
    '/care-team/find': {
      id: '/care-team/find'
      path: '/find'
      fullPath: '/care-team/find'
      preLoaderRoute: typeof CareTeamFindRouteImport
      parentRoute: typeof CareTeamRoute
    }
    '/care-team/request-sent': {
      id: '/care-team/request-sent'
      path: '/request-sent'
      fullPath: '/care-team/request-sent'
      preLoaderRoute: typeof CareTeamRequestSentRouteImport
      parentRoute: typeof CareTeamRoute
    }
    '/care/': {
      id: '/care/'
      path: '/'
      fullPath: '/care/'
      preLoaderRoute: typeof CareIndexRouteImport
      parentRoute: typeof CareRoute
    }
    '/care/$program': {
      id: '/care/$program'
      path: '/$program'
      fullPath: '/care/$program'
      preLoaderRoute: typeof CareProgramRouteImport
      parentRoute: typeof CareRoute
    }
    '/family/': {
      id: '/family/'
      path: '/'
      fullPath: '/family/'
      preLoaderRoute: typeof FamilyIndexRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/family/$memberId': {
      id: '/family/$memberId'
      path: '/$memberId'
      fullPath: '/family/$memberId'
      preLoaderRoute: typeof FamilyMemberIdRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/geofence/': {
      id: '/geofence/'
      path: '/'
      fullPath: '/geofence/'
      preLoaderRoute: typeof GeofenceIndexRouteImport
      parentRoute: typeof GeofenceRoute
    }
    '/geofence/alerts': {
      id: '/geofence/alerts'
      path: '/alerts'
      fullPath: '/geofence/alerts'
      preLoaderRoute: typeof GeofenceAlertsRouteImport
      parentRoute: typeof GeofenceRoute
    }
    '/geofence/settings': {
      id: '/geofence/settings'
      path: '/settings'
      fullPath: '/geofence/settings'
      preLoaderRoute: typeof GeofenceSettingsRouteImport
      parentRoute: typeof GeofenceRoute
    }
    '/geofence/zones': {
      id: '/geofence/zones'
      path: '/zones'
      fullPath: '/geofence/zones'
      preLoaderRoute: typeof GeofenceZonesRouteImport
      parentRoute: typeof GeofenceRoute
    }
    '/medication/': {
      id: '/medication/'
      path: '/'
      fullPath: '/medication/'
      preLoaderRoute: typeof MedicationIndexRouteImport
      parentRoute: typeof MedicationRoute
    }
    '/medication/add': {
      id: '/medication/add'
      path: '/add'
      fullPath: '/medication/add'
      preLoaderRoute: typeof MedicationAddRouteImport
      parentRoute: typeof MedicationRoute
    }
    '/medication/course': {
      id: '/medication/course'
      path: '/course'
      fullPath: '/medication/course'
      preLoaderRoute: typeof MedicationCourseRouteImport
      parentRoute: typeof MedicationRoute
    }
    '/medication/history': {
      id: '/medication/history'
      path: '/history'
      fullPath: '/medication/history'
      preLoaderRoute: typeof MedicationHistoryRouteImport
      parentRoute: typeof MedicationRoute
    }
    '/medication/refills': {
      id: '/medication/refills'
      path: '/refills'
      fullPath: '/medication/refills'
      preLoaderRoute: typeof MedicationRefillsRouteImport
      parentRoute: typeof MedicationRoute
    }
    '/medication/reminders': {
      id: '/medication/reminders'
      path: '/reminders'
      fullPath: '/medication/reminders'
      preLoaderRoute: typeof MedicationRemindersRouteImport
      parentRoute: typeof MedicationRoute
    }
    '/medication/review': {
      id: '/medication/review'
      path: '/review'
      fullPath: '/medication/review'
      preLoaderRoute: typeof MedicationReviewRouteImport
      parentRoute: typeof MedicationRoute
    }
    '/profile/$section': {
      id: '/profile/$section'
      path: '/$section'
      fullPath: '/profile/$section'
      preLoaderRoute: typeof ProfileSectionRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/records/': {
      id: '/records/'
      path: '/'
      fullPath: '/records/'
      preLoaderRoute: typeof RecordsIndexRouteImport
      parentRoute: typeof RecordsRoute
    }
    '/records/$category': {
      id: '/records/$category'
      path: '/$category'
      fullPath: '/records/$category'
      preLoaderRoute: typeof RecordsCategoryRouteImport
      parentRoute: typeof RecordsRoute
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/twin/$system': {
      id: '/twin/$system'
      path: '/$system'
      fullPath: '/twin/$system'
      preLoaderRoute: typeof TwinSystemRouteImport
      parentRoute: typeof TwinRoute
    }
    '/vitals/$metric': {
      id: '/vitals/$metric'
      path: '/vitals/$metric'
      fullPath: '/vitals/$metric'
      preLoaderRoute: typeof VitalsMetricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-team/caregiver/$caregiverId': {
      id: '/care-team/caregiver/$caregiverId'
      path: '/caregiver/$caregiverId'
      fullPath: '/care-team/caregiver/$caregiverId'
      preLoaderRoute: typeof CareTeamCaregiverCaregiverIdRouteImport
      parentRoute: typeof CareTeamRoute
    }
    '/records/doc/$id': {
      id: '/records/doc/$id'
      path: '/doc/$id'
      fullPath: '/records/doc/$id'
      preLoaderRoute: typeof RecordsDocIdRouteImport
      parentRoute: typeof RecordsRoute
    }
  }
}

interface CareRouteChildren {
  CareProgramRoute: typeof CareProgramRoute
  CareIndexRoute: typeof CareIndexRoute
}

const CareRouteChildren: CareRouteChildren = {
  CareProgramRoute: CareProgramRoute,
  CareIndexRoute: CareIndexRoute,
}

const CareRouteWithChildren = CareRoute._addFileChildren(CareRouteChildren)

interface CareTeamRouteChildren {
  CareTeamCaregiversRoute: typeof CareTeamCaregiversRoute
  CareTeamFindRoute: typeof CareTeamFindRoute
  CareTeamRequestSentRoute: typeof CareTeamRequestSentRoute
  CareTeamIndexRoute: typeof CareTeamIndexRoute
  CareTeamCaregiverCaregiverIdRoute: typeof CareTeamCaregiverCaregiverIdRoute
}

const CareTeamRouteChildren: CareTeamRouteChildren = {
  CareTeamCaregiversRoute: CareTeamCaregiversRoute,
  CareTeamFindRoute: CareTeamFindRoute,
  CareTeamRequestSentRoute: CareTeamRequestSentRoute,
  CareTeamIndexRoute: CareTeamIndexRoute,
  CareTeamCaregiverCaregiverIdRoute: CareTeamCaregiverCaregiverIdRoute,
}

const CareTeamRouteWithChildren = CareTeamRoute._addFileChildren(
  CareTeamRouteChildren,
)

interface FamilyRouteChildren {
  FamilyMemberIdRoute: typeof FamilyMemberIdRoute
  FamilyIndexRoute: typeof FamilyIndexRoute
}

const FamilyRouteChildren: FamilyRouteChildren = {
  FamilyMemberIdRoute: FamilyMemberIdRoute,
  FamilyIndexRoute: FamilyIndexRoute,
}

const FamilyRouteWithChildren =
  FamilyRoute._addFileChildren(FamilyRouteChildren)

interface GeofenceRouteChildren {
  GeofenceAlertsRoute: typeof GeofenceAlertsRoute
  GeofenceSettingsRoute: typeof GeofenceSettingsRoute
  GeofenceZonesRoute: typeof GeofenceZonesRoute
  GeofenceIndexRoute: typeof GeofenceIndexRoute
}

const GeofenceRouteChildren: GeofenceRouteChildren = {
  GeofenceAlertsRoute: GeofenceAlertsRoute,
  GeofenceSettingsRoute: GeofenceSettingsRoute,
  GeofenceZonesRoute: GeofenceZonesRoute,
  GeofenceIndexRoute: GeofenceIndexRoute,
}

const GeofenceRouteWithChildren = GeofenceRoute._addFileChildren(
  GeofenceRouteChildren,
)

interface MedicationRouteChildren {
  MedicationAddRoute: typeof MedicationAddRoute
  MedicationCourseRoute: typeof MedicationCourseRoute
  MedicationHistoryRoute: typeof MedicationHistoryRoute
  MedicationRefillsRoute: typeof MedicationRefillsRoute
  MedicationRemindersRoute: typeof MedicationRemindersRoute
  MedicationReviewRoute: typeof MedicationReviewRoute
  MedicationIndexRoute: typeof MedicationIndexRoute
}

const MedicationRouteChildren: MedicationRouteChildren = {
  MedicationAddRoute: MedicationAddRoute,
  MedicationCourseRoute: MedicationCourseRoute,
  MedicationHistoryRoute: MedicationHistoryRoute,
  MedicationRefillsRoute: MedicationRefillsRoute,
  MedicationRemindersRoute: MedicationRemindersRoute,
  MedicationReviewRoute: MedicationReviewRoute,
  MedicationIndexRoute: MedicationIndexRoute,
}

const MedicationRouteWithChildren = MedicationRoute._addFileChildren(
  MedicationRouteChildren,
)

interface ProfileRouteChildren {
  ProfileSectionRoute: typeof ProfileSectionRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileSectionRoute: ProfileSectionRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface RecordsRouteChildren {
  RecordsCategoryRoute: typeof RecordsCategoryRoute
  RecordsIndexRoute: typeof RecordsIndexRoute
  RecordsDocIdRoute: typeof RecordsDocIdRoute
}

const RecordsRouteChildren: RecordsRouteChildren = {
  RecordsCategoryRoute: RecordsCategoryRoute,
  RecordsIndexRoute: RecordsIndexRoute,
  RecordsDocIdRoute: RecordsDocIdRoute,
}

const RecordsRouteWithChildren =
  RecordsRoute._addFileChildren(RecordsRouteChildren)

interface ReportsRouteChildren {
  ReportsIdRoute: typeof ReportsIdRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsIdRoute: ReportsIdRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface TwinRouteChildren {
  TwinSystemRoute: typeof TwinSystemRoute
}

const TwinRouteChildren: TwinRouteChildren = {
  TwinSystemRoute: TwinSystemRoute,
}

const TwinRouteWithChildren = TwinRoute._addFileChildren(TwinRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CareRoute: CareRouteWithChildren,
  CareTeamRoute: CareTeamRouteWithChildren,
  CompanionRoute: CompanionRoute,
  FamilyRoute: FamilyRouteWithChildren,
  GeofenceRoute: GeofenceRouteWithChildren,
  HomeRoute: HomeRoute,
  MedicationRoute: MedicationRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PremiumRoute: PremiumRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RecordsRoute: RecordsRouteWithChildren,
  ReportsRoute: ReportsRouteWithChildren,
  TwinRoute: TwinRouteWithChildren,
  VitalsMetricRoute: VitalsMetricRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
